dist: bionic
language: python
jobs:
  include:
  - os: linux
    python: 3.6
    sudo: true
    env:
    - BUILD=PYPI
  - os: linux
    python: 3.7
    sudo: true
  - os: linux
    python: 3.8
    sudo: true
install:
- pip install poetry
- poetry config virtualenvs.create false
- poetry install
script:
- flakehell lint
- pytest
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  user: __token__
  on:
    tags: true
    distributions: sdist
    condition: "$BUILD = PYPI"
    repo: cloudblue/connect-python-openapi-client
