name: Build Connect Python OpenAPI Client

on:
  push:
    branches: [ master, develop ]
    tags:
        - '*'
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Linting
      run: |
        poetry run flakehell lint
    - name: Testing
      run: |
        poetry run pytest
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
  deploy:
      if: ${{ github.event.release.types == 'created' }}
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python
          uses: actions/setup-python@v2
          with:
          python-version: '3.x'
      - name: Install dependencies
          run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
          env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*